sqlite:
  path: "/data/leistungs_db.sqlite"
google: "YOUR_API_KEY"
bot_token: "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
api_hash: "your-api-hash"
api_id: "your-api-id"
chat_id: "your-chat-id"
leistungschat_id: "your-leistungschat-id"
leistungsadmin_id: "your-leistungsadmin-id"
usernames:
  - "your-username"
backupchat_id: "your-backup-channel-id"
