version: "3.9"
services:
  leistungsbot:
    build: .
    volumes:
      - ./BotConfig.yml:/config/BotConfig.yml:ro
    links:
      - "db:mysql"
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: "leistungs_db"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "leistungs_user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "8JpoPax7TEyGCY"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
      # Where our data will be persisted
    ports:
      - 3306:3306
    volumes:
      - ./example_db:/var/lib/mysql
  phpmyadmin:
    image: beeyev/phpmyadmin-lightweight:latest
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
