version: "3.9"
services:
  leistungsbot:
    build: .
    volumes:
      - ./BotConfig.yml:/config/BotConfig.yml:ro
    links:
      - "db:mysql"
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: 'leistungs_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'leistungs_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: '8JpoPax7TEyGCY'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      # Where our data will be persisted
    volumes:
      - leistungs_db_data:/var/lib/mysql

volumes:
  leistungs_db_data: